//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.BackOffice.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCardDetail
    {
        public int CardDetailID { get; set; }
        public string MaskedCardNo { get; set; }
        public Nullable<int> CardTypeMasterID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CardToken { get; set; }
    }
}
