//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.BackOffice.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReservationDocument
    {
        public int ReservationdocumentID { get; set; }
        public Nullable<int> ReservationDetailID { get; set; }
        public Nullable<int> ReseDocTypeMasterID { get; set; }
        public byte[] Document { get; set; }
    }
}
