//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.BackOffice.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReservationDetail
    {
        public int ReservationDetailID { get; set; }
        public string ReservationNameID { get; set; }
        public string ReservationNumber { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<int> Adultcount { get; set; }
        public Nullable<int> Childcount { get; set; }
        public string MembershipNo { get; set; }
        public string MembershipType { get; set; }
        public Nullable<bool> IsDepositAvailable { get; set; }
        public Nullable<bool> IsCardDetailPresent { get; set; }
        public Nullable<int> CardDetailID { get; set; }
        public Nullable<bool> IsSaavyPaid { get; set; }
        public Nullable<System.DateTime> DataInsertedDate { get; set; }
        public Nullable<System.DateTime> Dataupdateddate { get; set; }
        public Nullable<bool> IsPushedToCloud { get; set; }
        public Nullable<System.DateTime> CloudPushedDateTime { get; set; }
        public Nullable<bool> IsFetchedFromCloud { get; set; }
        public Nullable<System.DateTime> CloudFetchDateTime { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string ReservationSource { get; set; }
        public string StatusDescription { get; set; }
        public string RoomType { get; set; }
        public string RoomTypeDescription { get; set; }
        public string RoomNumber { get; set; }
        public Nullable<bool> IsBreakFastAvailable { get; set; }
        public Nullable<bool> IsPreCheckedInPMS { get; set; }
        public Nullable<bool> EmailSent { get; set; }
    }
}
